const columns = [
	{name: 'ID', uid: 'id', sortable: true},
	{name: 'STUDENT NAME', uid: 'student_name', sortable: true},
	{name: 'CLASS', uid: 'class', sortable: true},
	{name: 'GROUP', uid: 'group', sortable: true},
	{name: 'EMAIL', uid: 'email'},
	{name: 'STATUS', uid: 'status', sortable: true},
	{name: 'INFORMATIONS', uid: 'informations'},
];

const statusOptions = [
	{name: 'Present', uid: 'present'},
	{name: 'Absent', uid: 'absent'},
];

export const data = {
	users : [
		{
			id: 1,
			student_name: 'Jane Cooper',
			class: 'M2_APP',
			group: 'DE',
			email: 'tony.reichert@example.com',
			status: 'Present',
			informations: 3,
		},
		{
			id: 2,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 1,
		},
		{
			id: 3,
			student_name: 'Ronald Richards',
			class: 'M2_APP',
			group: 'LSI',
			email: 'ronald.richards@efrei.net',
			status: 'Absent',
			informations: 0,
		},
		{
			id: 4,
			student_name: 'Marvin McKinney',
			class: 'M2_APP',
			group: 'LSI',
			email: 'marvin.mckinney@efrei.net',
			status: 'Present',
			informations: 2,
		},
		{
			id: 5,
			student_name: 'Jerome Bell',
			class: 'M2_APP',
			group: 'DT',
			email: 'jerome.bell@efrei.net',
			status: 'Present',
			informations: 1,
		},
		{
			id: 6,
			student_name: 'Kathryn Murphy',
			class: 'M2_APP',
			group: 'DE',
			email: 'floyd.miles@efrei.net',
			status: 'Present',
			informations: 2,
		},
		{
			id: 7,
			student_name: 'Jacob Jones',
			class: 'M2_APP',
			group: 'SE',
			email: 'jacob.jones@efrei.net',
			status: 'Present',
			informations: 3,
		},
		{
			id: 8,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},
		{
			id: 9,
			student_name: 'Kristin Watson',
			class: 'M2_APP',
			group: 'DT',
			email: 'kristin.watson@efrei.net',
			status: 'Absent',
			informations: 1,
		},
		{
			id: 10,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 11,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 12,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 13,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 14,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 15,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 16,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 17,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 18,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 19,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},{
			id: 20,
			student_name: 'Floyd Miles',
			class: 'M2_APP',
			group: 'SE',
			email: 'floyd.miles@efrei.net',
			status: 'Absent',
			informations: 0,
		},
	]
};

export {columns, statusOptions};
